development:
    clients:
        default:
            database: rails_develop
            hosts:
                - localhost:27017
            options:
                user: didi
                password: 123qweasd
               # (default: the database specified above or admin)
                auth_source: rails_develop

                # Force a the driver cluster to behave in a certain manner instead of auto-
                # discovering. Can be one of: :direct, :replica_set, :sharded. Set to :direct
                # when connecting to hidden members of a replica set.
                # connect: :direct

                # Changes the default time in seconds the server monitors refresh their status
                # via ismaster commands. (default: 10)
                # heartbeat_frequency: 10

                # The time in seconds for selecting servers for a near read preference. (default: 0.015)
                # local_threshold: 0.015

                # The timeout in seconds for selecting a server for an operation. (default: 30)
                # server_selection_timeout: 30

                # The maximum number of connections in the connection pool. (default: 5)
                # max_pool_size: 5

                # The minimum number of connections in the connection pool. (default: 1)
                # min_pool_size: 1

                # The time to wait, in seconds, in the connection pool for a connection
                # to be checked in before timing out. (default: 5)
                # wait_queue_timeout: 5

                # The time to wait to establish a connection before timing out, in seconds.
                # (default: 5)
                # connect_timeout: 5

                # The timeout to wait to execute operations on a socket before raising an error.
                # (default: 5)
                # socket_timeout: 5

                # The name of the replica set to connect to. Servers provided as seeds that do
                # not belong to this replica set will be ignored.
                # replica_set: name

                # Whether to connect to the servers via ssl. (default: false)
                # ssl: true

                # The certificate file used to identify the connection against MongoDB.
                # ssl_cert: /path/to/my.cert

                # The private keyfile used to identify the connection against MongoDB.
                # Note that even if the key is stored in the same file as the certificate,
                # both need to be explicitly specified.
                # ssl_key: /path/to/my.key

                # A passphrase for the private key.
                # ssl_key_pass_phrase: password

                # Whether or not to do peer certification validation. (default: true)
                # ssl_verify: true

                # The file containing a set of concatenated certification authority certifications
                # used to validate certs passed from the other end of the connection.
                # ssl_ca_cert: /path/to/ca.cert

                # Configure Mongoid specific options. (optional)
                options:
                    test:
                        clients:
                            default:
                                database: rails_test
                    hosts:
                        - localhost:27017
                    options:
                        user: didi
                        password: 123qweasd
                        auth_source: rails_test
                    read:
                        mode: :primary
                    max_pool_size: 1
